### ISSUE TITLE
Show Necessary Information

### ISSUE THREAD

**Issue by yashpatel458** [clubgamma/Weather-Web-App#1]
It should show the weather of a particular city in brief. Play with API and get something useful to show up and avoid unnecessary data.

**Comment by Deeprana12** [comment]
Hey, @yashpatel458 I'm on it.

**Comment by yashpatel458** [comment]
> Hey, @yashpatel458 I'm on it.

Hey @Deeprana12, Thank you for showing interest in contributing to this project. As this project is marked for Hacktoberfest, you can start contributing from 1st October!

**Comment by Deeprana12** [comment]
Kindly assign the task to me @yashpatel458
