### ISSUE TITLE
Invalid response from the API

### ISSUE THREAD

**Issue by saheelsapovadia** [clubgamma/Weather-Web-App#15]
Can someone give proper steps to set up this project, it shows the following -
@Deeprana12 @yashpatel458 
![image](https://user-images.githubusercontent.com/59962703/135699740-14517bce-5a36-44fc-90ef-ff5fe03b18bb.png)

**Comment by Deeprana12** [comment]
If someone will enter a city that doesn't exist it will throw the above Error. Though I'll check it again & add the proper steps.
@saheelsapovadia

**Comment by yashpatel458** [comment]
> Can someone give proper steps to set up this project, it shows the following -
> @Deeprana12 @yashpatel458 
> ![image](https://user-images.githubusercontent.com/59962703/135699740-14517bce-5a36-44fc-90ef-ff5fe03b18bb.png)
> 

Does this happen with every city?

**Comment by Deeprana12** [comment]
No, only for invalid cities but the issue is resolved there's nothing to change!! If still gettting this issue then please fetch and merge again.

**Comment by coder483** [comment]
hey  can i work on this

**Comment by Deeprana12** [comment]
clone the repo in you remote, then put your API in index.js(first line) and then check if it working or not? I think it's working fine don't know why they are keeping this issue open.
